config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "notes#index"
  resources :users, only: [:edit, :update]
  resources :notes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end
  
  def new
    @note = Note.new
  end
  
	def create
		@note = Note.new(note_params)
		if @note.save
      redirect_to note_path(@note)
		else
			flash.now[:alert] = '保存できませんでした'
      render :new
    end
    # Note.create(note_params)
    # redirect_to new_note_path

  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    note = Note.find(params[:id])
    note.update(note_params)
    redirect_to note_path(note.id)
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end

  private
  def note_params
    params.require(:note).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.haml
-if model.errors.any?
  .alert
    %ul
      -model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_notifications.html.haml
.notification
	- flash.each do |key, value|
		= content_tag(:div, value, class: key)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title VoiceNote
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/notes/_main.html.haml
.main
  .main__header
  .main__content
    .main__content__app-name
      Voice note
    .main__content__manual
      .main__content__manual__plus
        = icon('far','plus-square',class: "plus-square")
        新規作成ボタン
      .main__content__manual__cog
        = icon('fas','cog',class: "cog")
        ユーザー情報編集ボタン（ここからログアウト）

app/views/notes/_main_new.html.haml
.new__main
  = form_for @note do |f|
    = render 'layouts/error_messages', model: f.object
    .new__main__header
      .new__main__header__title
        = f.text_field :title, class: 'title',placeholder: "title"
      .new__main__header__btn
        .new__main__header__btn--start
          %button{type: "button", id:'start-btn'} 
            = "start"
        .new__main__header__btn--stop
          %button{type: "button", id:'stop-btn'} 
            = "stop"
        .new__main__header__btn--save
          = f.submit "save", id: 'save-btn'
    .new__main__content
      = f.text_area :content, class: 'text', placeholder: 'type a text', id: 'content', size: "113x25", style: "border:none"

app/views/notes/_main_show.html.haml
.show__main
  .show__main__header
    .show__main__header__title
      = @note.title
    .show__main__header__btn
      .show__main__header__btn--edit
        = link_to edit_note_path(@note.id), class: "edit" do
          %button{type: "button", id:'edit-btn'} 
            = "edit"
      .show__main__header__btn--delete
        = link_to note_path(@note.id), method: :delete, class: "delete" do
          %button{type: "button", id:'delete-btn'} 
            = "delete"
  .show__main__content
    = @note.content

app/views/notes/_side.html.haml
.side
  .side__header
    .side__header__box
      .side__header__box__user-name
        = current_user.name
      .side__header__box__icons
        .side__header__box__icons--plus
          = link_to new_note_path, class: "icon-plus" do
            = icon('far','plus-square')
        .side__header__box__icons--cog
          = link_to edit_user_path(current_user), class: "icon-cog" do
            = icon('fas','cog')
  .side__list
    - current_user.notes.each do |note|
      .side__list__note
        = link_to note_path(note.id) do
          .side__list__note__title
            = note.title
    .side__list__search

app/views/notes/edit.html.haml
.wrapper
  = render "side"
  = render "main_new"

app/views/notes/index.html.haml
.wrapper
  = render "side"
  = render "main"

app/views/notes/new.html.haml
.wrapper
  = render "side"
  = render "main_new"

app/views/notes/show.html.haml
.wrapper
  = render "side"
  = render "main_show"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", root_path, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'